# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name find_best_split_rcpp
#' @title Find the Best Split Using Rcpp
#' @description This function finds the best feature and threshold to split data using Gini impurity, implemented with Rcpp for speed.
#' @param data A numeric matrix where rows represent observations and columns represent features.
#' @param target An integer vector containing the target variable (class labels) corresponding to the rows of \code{data}.
#' @return A list containing:
#' \itemize{
#'   \item \code{feature}: The index of the best feature to split on.
#'   \item \code{threshold}: The threshold value of the best split for the feature.
#' }
#' @examples
#' \dontrun{
#' data <- matrix(runif(100), nrow = 10, ncol = 10)
#' target <- sample(0:1, 10, replace = TRUE)
#' best_split <- find_best_split_rcpp(data, target)
#' print(best_split)
#' }
#' @export
find_best_split_rcpp <- function(data, target) {
    .Call('_SA24204128_find_best_split_rcpp', PACKAGE = 'SA24204128', data, target)
}

